In [4]:
#Esercizio Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
#Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione 
#Come facciamo per accedere ad un elemento in particolare?
#Esercizio Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos()
#.factorial() e la variabile .pi la riconoscete?
import math
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
math.sin(9)

0.4121184852417566

In [5]:
math.cos(5)

0.28366218546322625

In [6]:
math.factorial(6)

720

In [8]:
math.pi

3.141592653589793

In [9]:
#Esercizio Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il
#risultato? Per saperne di più su questa funzione possiamo usare 
#help(math.degrees)
math.degrees(math.pi)

180.0

In [11]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [7]:
import numpy as np
import pandas as pd


In [22]:
#Esercizio L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
#lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un array NumPy (casting): 
#lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: • qual è stata la vendita massima mensile? E quella minima? • 
#quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? • quali sono le vendite minori di 3000 oggetti?

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)
print(lst.max())                 #VENDITA MASSIMALE
print(lst.min())                 #VENDITA MINIMA

filter_lst = lst > 5000          #VENDITE MAGGIORI DI 5000
print(lst[filter_lst])

filter_lst2 = lst < 3000         #VENDITE MINORI DI 3000
print(lst[filter_lst2])

print(lst.mean())                 #MEDIA


8150
1280
[5500 7200 6410 8150 7100 5350]
[2000 1280 1900 2500]
4634.166666666667


In [8]:
#Esercizio Consideriamo il seguente dizionario:
#fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#Consideriamo ora la seguente Series: fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
#index=range(1997, 2005)) Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997]
#Dunque qual è la differenza tra i due tipi di dato?  Cosa potremmo fare con la Series che non possiamo fare con il dizionario?

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
                              index=range(1997, 2005))      
print(fatturati_dict[1997])
print(fatturati_series[1997])

#Qual è la differenza tra i due tipi di dato? 
#DICTIONARY HA UNA STRUTTURA NON ORDINATA E NON SUPPORTA L'INDEXING, SERIES E' UN ARRAY INDICIZATO.

#Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
#L'INDEXING, OVVERO L'INDICE.



12000
12000


In [45]:
#Esercizio L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: import numpy as np
#stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) 
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: • con un ciclo for • con un masking

import numpy as np
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) 
print(stipendi * 2)

for stipendio in stipendi:
   print(stipendio * 2 )

for stipendio in stipendi:
    stipendio_molt = stipendio * 2 
    print(stipendio_molt)
    
mask = stipendi > 10
stipendi[mask] * 2




[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
200
400
600
800
1000
1200
1400
1600
1800
2000
200
400
600
800
1000
1200
1400
1600
1800
2000


array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [1]:
#Esercizio Scrivere un programma che • in input acquisisce una lista di numeri e un numero K • in output, dovrà restituire la media di tutti i numeri 
#nella lista maggiori o uguali a K • se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.
import numpy as np

numeri = [50, 600, 120, 85, 23, 30, 29, 100, 120, 30, 25, 23, 35, 600, 45, 29, 45]
K = 80

dati = np.array(numeri)
filtro = dati >= K 
datiK = dati[filtro]
print(datiK)

datiK.mean().round()



[600 120  85 100 120 600]


271.0

In [18]:
#Esercizio Scrivere un programma che, data una lista di numeri, come output stamperà lo stesso numero di asterischi su righe diverse,
#ottenendo una semplice visualizzazione grafica

numeri = [5, 3, 4, 8,10,7,1]

for numero in numeri:
    print("*" * numero)

#se volessimo avere anche il numero con gli asterischi faremo:
for numero in numeri:
    print(numero, "*" * numero)
    



*****
***
****
********
**********
*******
*
5 *****
3 ***
4 ****
8 ********
10 **********
7 *******
1 *


In [32]:
#Esercizio Abbiamo una lista di codici fiscali:
#lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
#• trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla;
#•inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome.

lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

lista_cf_95 = []

for cf in lista_cf:
 if "95" in cf:
    lista_cf_95.append(cf)                     #AGGIUNGO ALLA LISTA
    print(cf, "-", cf[:3], cf[3:6])

  

ABCDEF95G01A123B - ABC DEF
STUVWX95Z04A654E - STU VWX
DEFGHI95J06A987G - DEF GHI


In [1]:
#Esercizio Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente: 
#studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
#corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
#edizioni = [1, 2, 3, 2, 2, 1, 3, 3] • Stampare a video tutti e soli gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

for i in range(len(studenti)):
    if edizioni[i] == 1:
        print(studenti[i])

Alex
Faith


In [2]:
#Esercizio Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro:
#prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; 
#il risultato sarà memorizzato in un'altra lista.

prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
prezzi_corretti = []

for prezzo in prezzi:
    nuovo_prezzo = prezzo.replace("€", "$")
    prezzi_corretti.append(nuovo_prezzo)

print(prezzi_corretti)

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [5]:
#Esercizio Abbiamo una lista di studenti: studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] vogliamo dividere gli studenti in due 
#squadre per un campionato di Uno nel seguente modo: selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra.
#Creiamo due liste per ogni squadra, e alla fine visualizziamole.

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
squadra_pari = []
squadra_dispari = []

for i in range(len(studenti)):
    if i % 2 == 0:                                                  # indice pari
        squadra_pari.append(studenti[i])
    else:                                                           # indice dispari
        squadra_dispari.append(studenti[i])

print("Squadra posizioni pari:", squadra_pari)
print("Squadra posizioni dispari:", squadra_dispari)

Squadra posizioni pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Squadra posizioni dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']
